CREATE TABLE IF NOT EXISTS customers(
	customer_id INT GENERATED BY DEFAULT AS IDENTITY,
	customer_name varchar(50),
	customer_age INT NOT NULL,
	customer_email varchar(256) NOT NULL,
	customer_login varchar(256) NOT NULL UNIQUE,
	customer_password varchar(256) NOT NULL,
	bank_card varchar(256) NOT NULL UNIQUE,
	customer_role varchar(50) DEFAULT 'user',
	PRIMARY KEY(customer_id),
	CHECK(customer_age >= 18),
	CHECK(LENGTH(customer_login)>=6),
	CHECK(LENGTH(customer_password)>=6)
);

create or replace function register_customer(
	customer_login_v customers.customer_login%type,
    customer_password_v customers.customer_password%type,
    customer_name_v customers.customer_name%type,
    customer_age_v customers.customer_age%type,
    customer_email_v customers.customer_email%type,
	bank_card_v customers.bank_card%type
) returns text
language plpgsql
as
$body$
declare
   status text;
begin

	IF customer_name_v LIKE '' then
	customer_name_v := NULL;
	END IF;

	INSERT INTO customers(customer_name,customer_age,customer_email,customer_login,customer_password,bank_card)
	VALUES (customer_name_v,customer_age_v,customer_email_v,customer_login_v,customer_password_v,bank_card_v);
	status := 'Done!';

	return status;
	exception
	   when others then
	      status := 'Error!';
		  return status;
end;
$body$